github.com:
    git_protocol: https
    users:
        NotRealSean:
            oauth_token: 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
    user: NotRealSean
    oauth_token: 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
